
targets:
  $default:
    builders:
      freezed:
        options:
          # Tells Freezed not to format .freezed.dart files.
          # This can significantly speed up code-generation.
          # format: false
          # # `when` and `map` can be enabled/disabled entirely by setting them to `true`/`false`
          # map: false
          # We can also enable/disable specific variants of `when`/`map` by setting them to `true`/`false`:
          when:
            when: true
            maybe_when: true
            when_or_null: true
      drift_dev:
        options:
          write_from_json_string_constructor: true
          mutable_classes: true
