// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTRC-QCzJTHDVaIibNUkZ7tk3BtQbXXZY',
    appId: '1:1031438051281:android:13fd8c96834e10b7af62f0',
    messagingSenderId: '1031438051281',
    projectId: 'deenhub-4bf96',
    storageBucket: 'deenhub-4bf96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMWCXb-cT2rIqfeRctgysZ3oyRD_NHsXk',
    appId: '1:1031438051281:ios:37b5c72e135257c8af62f0',
    messagingSenderId: '1031438051281',
    projectId: 'deenhub-4bf96',
    storageBucket: 'deenhub-4bf96.firebasestorage.app',
    androidClientId: '1031438051281-13a7j65td4ovpqugok5gdmbnlicgci3m.apps.googleusercontent.com',
    iosClientId: '1031438051281-4uemg3422hkpo4c0h9c65pq19m3qlb83.apps.googleusercontent.com',
    iosBundleId: 'com.deenhub.app',
  );

}